# Fetching the latest node image on alpine linux
FROM node:17-alpine as builder

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /app

# Installing dependencies
COPY package.json .
RUN npm install

# Copying all the files in our project
COPY . .

# Run on port 3000
EXPOSE 3000

# Execute this command to start
CMD ["npm", "start"]